### ISSUE TITLE
Inconsistent behavior with patrolling NPCs

### ISSUE THREAD

**Issue by spicydinosaur** [spicydinosaur/AnxietyGame#3]
Most recent build for this project is under the Spicy-Branch, several NPCs were added at the time it was worked on, and this is when I noticed the issue outside of the one NPC that had all three of the involved scripts for a long time before this. (The dog.)

Currently (most) NPCs, specifically any that patrol an area, have a child gameobject with a script that has them stop if they collide with the hero of the game. However, sometimes an NPC, (especially the dog it seems, but I might just think this because this was the first time I noticed it,) will not go back to patrolling, but will instead just permanently stop for the remainder of the time the program is on play mode. 

I suspect conflicts between: NPCController, NPCPatrolRoute, (which work in conjunction with one another,) and StopOnTrigger (the script attached to the child gameobject, StopOnCollision.)

The offending NPCs can be found as children of the Seaside Village gameobject. Only one of the NPCs, Mabel, does not have these scripts attached, because she does not patrol. I have verified this misbehavior with the dog and the girl child at the very least, but there is no differences I can think of that would make the other patrolling NPCs behave less erratically.

There may be something else afoot, as I recently changed NPC Rigidbodies to kinematic from dynamic. I have no idea if that would cause anything weird in this regard.

Note that if you open the whole project, PillarInteraction will throw up bugs because it is currently half finished.

**Comment by elfasiShir** [comment]
Hello, im willing to contribute, please assign me
